insert into WRK.roles (role) value ("ADMIN");
insert into WRK.roles (role) value ("USER");

insert into WRK.parts (catalogNumber, name, quantity, type) VALUE ("FABORY", "Podkladka M12", "100", "Podkladka");
insert into WRK.parts (catalogNumber, name, quantity, type) VALUE ("FABORY", "Podkladka M10", "100", "Podkladka");
insert into WRK.parts (catalogNumber, name, quantity, type) VALUE ("WRK", "Blaszka dociskowa 4F 330", "100", "Blaszka");
insert into WRK.parts (catalogNumber, name, quantity, type) VALUE ("WRK", "Blaszka dociskowa 4F 300", "100", "Blaszka");
insert into WRK.parts (catalogNumber, name, quantity, type) VALUE ("WRK", "Blaszka dociskowa 4C", "100", "Blaszka");
insert into WRK.parts (catalogNumber, name, quantity, type) VALUE ("WRK", "Blaszka dociskowa 6G", "100", "Blaszka");
insert into WRK.parts (catalogNumber, name, quantity, type) VALUE ("WRK", "Blaszka dociskowa 6F", "100", "Blaszka");
insert into WRK.parts (catalogNumber, name, quantity, type) VALUE ("WRK", "Blaszka dociskowa 6D", "100", "Blaszka");
insert into WRK.parts (catalogNumber, name, quantity, type) VALUE ("WRK", "Komplet uszcz. fi38", "100", "Blaszka");
insert into WRK.parts (catalogNumber, name, quantity, type) VALUE ("WRK", "Komplet uszcz. fi32", "100", "Blaszka");
insert into WRK.parts (catalogNumber, name, quantity, type) VALUE ("WRK", "Komplet uszcz. fi28", "100", "Blaszka");
insert into WRK.parts (catalogNumber, name, quantity, type) VALUE ("WRK", "Komplet uszcz. fi30", "100", "Blaszka");
insert into WRK.parts (catalogNumber, name, quantity, type) VALUE ("WRK", "Komplet uszcz. fi34", "100", "Blaszka");
insert into WRK.parts (catalogNumber, name, quantity, type) VALUE ("WRK", "Tloczek fi38 SPORT inox", "100", "Tloczek");
insert into WRK.parts (catalogNumber, name, quantity, type) VALUE ("WRK", "Tloczek fi32 SPORT inox", "100", "Tloczek");
insert into WRK.parts (catalogNumber, name, quantity, type) VALUE ("WRK", "Tloczek fi28 SPORT inox", "100", "Tloczek");
insert into WRK.parts (catalogNumber, name, quantity, type) VALUE ("WRK", "Tloczek fi38", "100", "Tloczek");
insert into WRK.parts (catalogNumber, name, quantity, type) VALUE ("WRK", "Tloczek fi34", "100", "Tloczek");
insert into WRK.parts (catalogNumber, name, quantity, type) VALUE ("WRK", "Tloczek fi28", "100", "Tloczek");
insert into WRK.parts (catalogNumber, name, quantity, type) VALUE ("WRK", "Dlawik do kabli", "100", "Dlawik");
insert into WRK.parts (catalogNumber, name, quantity, type) VALUE ("FABORY", "M10x90", "100", "Sruba");
insert into WRK.parts (catalogNumber, name, quantity, type) VALUE ("FABORY", "M10x80", "100", "Sruba");
insert into WRK.parts (catalogNumber, name, quantity, type) VALUE ("FABORY", "M10x75", "100", "Sruba");
insert into WRK.parts (catalogNumber, name, quantity, type) VALUE ("FABORY", "M10x70", "100", "Sruba");
insert into WRK.parts (catalogNumber, name, quantity, type) VALUE ("FABORY", "M6x20", "100", "Sruba");
insert into WRK.parts (catalogNumber, name, quantity, type) VALUE ("WRK", "RURKA 4F 330", "100", "Rurka");
insert into WRK.parts (catalogNumber, name, quantity, type) VALUE ("WRK", "RURKA 4F 300", "100", "Rurka");
insert into WRK.parts (catalogNumber, name, quantity, type) VALUE ("WRK", "RURKA 4C", "100", "Rurka");
insert into WRK.parts (catalogNumber, name, quantity, type) VALUE ("WRK", "RURKA 6G", "100", "Rurka");
insert into WRK.parts (catalogNumber, name, quantity, type) VALUE ("WRK", "RURKA 6F", "100", "Rurka");
insert into WRK.parts (catalogNumber, name, quantity, type) VALUE ("WRK", "RURKA 6D", "100", "Rurka");
insert into WRK.parts (catalogNumber, name, quantity, type) VALUE ("WP-Przewody hamulcowe", "Odpowietrznik", "100", "Rurka");
insert into WRK.parts (catalogNumber, name, quantity, type) VALUE ("WRK", "WZMOCNIENIE L64.5", "100", "Wzmocnienie");
insert into WRK.parts (catalogNumber, name, quantity, type) VALUE ("WRK", "WZMOCNIENIE L72", "100", "Wzmocnienie");
insert into WRK.parts (catalogNumber, name, quantity, type) VALUE ("WRK", "WZMOCNIENIE L70", "100", "Wzmocnienie");
insert into WRK.parts (catalogNumber, name, quantity, type) VALUE ("WRK", "WZMOCNIENIE L76", "100", "Wzmocnienie");
insert into WRK.parts (catalogNumber, name, quantity, type) VALUE ("WRK", "WZMOCNIENIE L74", "100", "Wzmocnienie");


insert into WRK.customers(NIP, PESEL, companyName, email, firstName, lastName, phoneNumber) VALUE ("113123123","12233341124","CodersLAB","test@test.pl","Sebastian","Taflinski","212312444");
insert into WRK.customers(NIP, PESEL, companyName, email, firstName, lastName, phoneNumber) VALUE ("222333111","12233341124","CodersLAB","test@test.pl","Bartek","Ostalowski","321123321");
insert into WRK.customers(NIP, PESEL, companyName, email, firstName, lastName, phoneNumber) VALUE ("411235511","12233341124","CodersLAB","test@test.pl","Maciek","Kozan","456654445");
insert into WRK.customers(NIP, PESEL, companyName, email, firstName, lastName, phoneNumber) VALUE ("222311123","12233341124","CodersLAB","test@test.pl","Dawid","Komar","654445666");
insert into WRK.customers(NIP, PESEL, companyName, email, firstName, lastName, phoneNumber) VALUE ("112331233","12233341124","CodersLAB","test@test.pl","Kuba","Mielnik","765858555");
